return {
    "folke/snacks.nvim",

    lazy = false,
    priority = 1000,

    keys = {
        { "<leader>bd", function() require("snacks").bufdelete() end, desc = "Delete current buffer" },

        { "<leader>gg", function() require("snacks").lazygit() end, desc = "Lazy git" },
        { "<leader>gl", function() require("snacks").lazygit.log() end, desc = "Git log" },
        { "<leader>gc", function() require("snacks").picker.git_branches() end, desc = "Git checkout" },

        { "<leader>sf", function() require("snacks").picker.files() end, desc = "Search files" },
        { "<leader>sg", function() require("snacks").picker.git_files() end, desc = "Search git files" },
        { "<leader>sG", function() require("snacks").picker.grep() end, desc = "Grep" },
        { "<leader>sG", function() require("snacks").picker.grep_word() end, desc = "Grep selection", mode = "x" },
        { "<leader>sb", function() require("snacks").picker.buffers() end, desc = "Search buffers" },
        { "<leader>sd", function() require("snacks").picker.diagnostics() end, desc = "Search diagnostics" },
        { "<leader>sD", function() require("snacks").picker.diagnostics_buffer() end, desc = "Search diagnostics (buffer)" },
        { "<leader>sk", function() require("snacks").picker.keymaps() end, desc = "Search keymaps" },

        { "<leader>ct", function() require("snacks").terminal() end, desc = "Open terminal" },

        { "<leader>ns", function() require("snacks").notifier.show_history() end, desc = "Show notifications" },
        { "<leader>nh", function() require("snacks").notifier.hide() end, desc = "Hide notifications" },
    },

    opts = {
        animate = { enabled = false },
        bigfile = { enabled = true },
        bufdelete = { enabled = true },
        dashboard = {
            enabled = true,
            pane_gap = 10,
            sections = {
                { section = "header" },
                { section = "keys", gap = 1, padding = 1 },
                {
                	desc = "Browse Repo",
                	icon = "",
                	action = function() require("snacks").gitbrowse() end,
                	key = "b",
                	pane = 2,
                	padding = 1,
                    enabled = function() return require("snacks").git.get_root() ~= nil end,
                },
                {
                    section = "terminal",
                    title = "Notifications",
                    icon = "",
                    cmd = "gh notify -s -a -n 5",
                    action = function() vim.ui.open("https://github.com/notifications") end,
                    pane = 2,
                    height = 5,
                    padding = 1,
                    indent = 2,
                    ttl = 5 * 60,
                    enabled = function() return require("snacks").git.get_root() ~= nil end,
                },
                {
                    section = "terminal",
                    title = "Git Status",
                    icon = "",
                    cmd = "git --no-pager diff --stat -B -M -C",
                    condition = function() return require("snacks").git.get_root() ~= nil end,
                    pane = 2,
                    height = 10,
                    padding = 1,
                    indent = 1,
                    ttl = 2 * 60,
                    enabled = function() return require("snacks").git.get_root() ~= nil end,
                },
                { section = "startup" },
			},
		},
		debug = { enabled = false },
		dim = { enabled = false },
		explorer = { enabled = false },
		gh = { enabled = false },
		git = { enabled = false },
		gitbrowse = { enabled = false },
		image = { enabled = false },
		indent = {
			enabled = true,
			char = "│",
			only_scope = true,
			only_current = true,
			hl = "SnacksIndent",
		},
		input = { enabled = false },
		keymap = { enabled = false },
		layout = { enabled = false },
		lazygit = { enabled = true },
		notifier = { enabled = true },
		notify = { enabled = true },
		picker = {
            enabled = true,
            win = {
                input = {
                    keys = {
                        ["<a-h>"] = nil, -- conflicts with aerospace
                        ["<a-t>"] = { "toggle_hidden", mode = { "i", "n" } },
                    },
                },
            },
        },
		profiler = { enabled = false },
		quickfile = { enabled = true },
		rename = { enabled = false },
		scope = { enabled = false },
		scratch = { enabled = false },
		scroll = { enabled = false },
		statuscolumn = { enabled = false },
		terminal = { enabled = true },
		toggle = { enabled = false },
		util = { enabled = false },
		win = { enabled = false },
		words = { enabled = false },
		zen = { enabled = false },
	},
}
